spring:
  security:
    oauth2:
      client:
        id: my-client
        secret: $2a$10$AcHaIKw4tg1VcmlmmpVkK.q1JP1xgpwehugM0gM4q45ZZBQVYdMfG #my-secret
        grant-types:
          - password
          - authorization_code
          - refresh_token
        scopes:
          - read
          - write
          - trust
        accessTokenValiditySeconds: -1
        refreshTokenValiditySeconds: -1
    user:
      name: test@test.com
      password: $2a$10$UvRO62xRebwdlwk7KbeCxuPw4IKQb5hDuq.zoPDlmZBPi.hpx92ES #tester